In [1]:
import pandas as pd

In [3]:
"""The bowlers with the best bowling figures at the end of the matches"""

'The bowlers with the best bowling figures at the end of the matches'

In [13]:
t20_data=pd.read_csv('t20-world-cup-22.csv')
t20_data.head()

,venue,team1,team2,stage,toss winner,toss decision,first innings score,first innings wickets,second innings score,second innings wickets,winner,won by,player of the match,top scorer,highest score,best bowler,best bowling figure
0,SCG,New Zealand,Australia,Super 12,Australia,Field,200.0,3.0,111.0,10.0,New Zealand,Runs,Devon Conway,Devon Conway,92.0,Tim Southee,3-6
1,Optus Stadium,Afghanistan,England,Super 12,England,Field,112.0,10.0,113.0,5.0,England,Wickets,Sam Curran,Ibrahim Zadran,32.0,Sam Curran,5-10
2,Blundstone Arena,Ireland,Sri lanka,Super 12,Ireland,Bat,128.0,8.0,133.0,1.0,Sri lanka,Wickets,Kusal Mendis,Kusal Mendis,68.0,Maheesh Theekshana,2-19
3,MCG,Pakistan,India,Super 12,India,Field,159.0,8.0,160.0,6.0,India,Wickets,Virat Kohli,Virat Kohli,82.0,Hardik Pandya,3-30
4,Blundstone Arena,Bangladesh,Netherlands,Super 12,Netherlands,Field,144.0,8.0,135.0,10.0,Bangladesh,Runs,Taskin Ahmed,Colin Ackermann,62.0,Taskin Ahmed,4-25

In [11]:
t20_data['best bowler'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 33 entries, 0 to 32
Series name: best bowler
Non-Null Count  Dtype
--------------  -----
30 non-null     object
dtypes: object(1)
memory usage: 396.0+ bytes

In [19]:
# here we have the best bowling figure 3-6 in this formate like wicktes and runs 

t20_data[['wickets','runs']]=t20_data['best bowling figure'].str.split('-',expand=True)

In [23]:
t20_data['wickets']=pd.to_numeric(t20_data['wickets'])
t20_data['runs']=pd.to_numeric(t20_data['runs'])
t20_data.head()

,venue,team1,team2,stage,toss winner,toss decision,first innings score,first innings wickets,second innings score,second innings wickets,winner,won by,player of the match,top scorer,highest score,best bowler,best bowling figure,wickets,runs
0,SCG,New Zealand,Australia,Super 12,Australia,Field,200.0,3.0,111.0,10.0,New Zealand,Runs,Devon Conway,Devon Conway,92.0,Tim Southee,3-6,3.0,6.0
1,Optus Stadium,Afghanistan,England,Super 12,England,Field,112.0,10.0,113.0,5.0,England,Wickets,Sam Curran,Ibrahim Zadran,32.0,Sam Curran,5-10,5.0,10.0
2,Blundstone Arena,Ireland,Sri lanka,Super 12,Ireland,Bat,128.0,8.0,133.0,1.0,Sri lanka,Wickets,Kusal Mendis,Kusal Mendis,68.0,Maheesh Theekshana,2-19,2.0,19.0
3,MCG,Pakistan,India,Super 12,India,Field,159.0,8.0,160.0,6.0,India,Wickets,Virat Kohli,Virat Kohli,82.0,Hardik Pandya,3-30,3.0,30.0
4,Blundstone Arena,Bangladesh,Netherlands,Super 12,Netherlands,Field,144.0,8.0,135.0,10.0,Bangladesh,Runs,Taskin Ahmed,Colin Ackermann,62.0,Taskin Ahmed,4-25,4.0,25.0

In [59]:
# lets find it 

t20_data=t20_data.sort_values(by=['wickets','runs'],ascending=[False,True])

best_bowling=t20_data.groupby('venue').first().reset_index()
best_bowling[['team1','team2','best bowler','wickets','runs','best bowling figure']]

,team1,team2,best bowler,wickets,runs,best bowling figure
0,Bangladesh,Pakistan,Shaheen Afridi,4.0,22.0,4-22
1,Bangladesh,Netherlands,Taskin Ahmed,4.0,25.0,4-25
2,Pakistan,England,Sam Curran,3.0,12.0,3-12
3,Afghanistan,England,Sam Curran,5.0,10.0,5-10
4,South Africa,Bangladesh,Anrich Nortje,4.0,10.0,4-10
5,Afghanistan,Sri lanka,Wanindu Hasaranga,3.0,13.0,3-13